info:
  component: Edge Server

server:
  port: 8765

eureka:
    instance:
        leaseRenewalIntervalInSeconds: 3
        metadataMap:
            instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
    client:
        registryFetchIntervalSeconds: 5
        instanceInfoReplicationIntervalSeconds: 5
        initialInstanceInfoReplicationIntervalSeconds: 5

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: "*"
  routes:
    apipath:
        path: /**
        serviceId: resourceapi
        stripPrefix: false
#    customersidepath:
#        path: /c/**
#        serviceId: resourceapi
#        stripPrefix: false
#    unitsidepath:
#        path: /u/**
#        serviceId: resourceapi
#        stripPrefix: false
#    testpath:
#        path: /t/**
#        serviceId: unitsidecomposite
#        stripPrefix: true
#    testpath2:
#        path: /t2/**
#        serviceId: resourceapi
#        stripPrefix: true
#    personapi:
#      path: /personapi/**
#      stripPrefix: false

logging:
  level:
    ROOT: WARN
    org.springframework.web: WARN
    com.netflix.hystrix: DEBUG

---
spring:
  profiles: docker

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
